version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    networks:
      - attendance-network
    depends_on:
      - db
      - mailtrap
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: attendance_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: attendance_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: attendance_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - attendance-network

  mailtrap:
    image: axllent/mailpit
    container_name: attendance_mailtrap
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - attendance-network

networks:
  attendance-network:
    driver: bridge

volumes:
  db_data:
    driver: local

